sudo: required

services:
  - docker

language: bash

env:
  global:
    - IMAGE_NAME=biarms/pgadmin4
    - PGADMIN_VERSION=2.1

before_install:
  - echo "PGADMIN_VERSION=$PGADMIN_VERSION - TRAVIS_BRANCH=$TRAVIS_BRANCH - DOCKER_USERNAME=$DOCKER_USERNAME"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - >
    mkdir tmp &&
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd

script: 
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - VCS_REF=$(git rev-parse --short HEAD)
  - docker build --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=$BUILD_DATE --build-arg PGADMIN_VERSION=$PGADMIN_VERSION -t $IMAGE_NAME:build .

after_success:
  - >
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "Building master branch. Let's push the new build on dockerhub"
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag $IMAGE_NAME:build $IMAGE_NAME:latest
      docker tag $IMAGE_NAME:build $IMAGE_NAME:$PGADMIN_VERSION
      docker push $IMAGE_NAME:latest
      docker push $IMAGE_NAME:$PGADMIN_VERSION
    else
      echo "Don't building master branch, but $TRAVIS_BRANCH. Push a beta version."
      docker tag $IMAGE_NAME:build $IMAGE_NAME:$PGADMIN_VERSION-beta
      docker push $IMAGE_NAME:$PGADMIN_VERSION-beta
    fi
