sudo: required

services:
  - docker

language: bash

env:
  global:
    - IMAGE_NAME=biarms/pgadmin4
    - PGADMIN_VERSION=2.1

before_install:
  - >
    echo "PGADMIN_VERSION=$PGADMIN_VERSION"
    echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
    echo "DOCKER_USERNAME=$DOCKER_USERNAME"
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script: 
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - VCS_REF=$(git rev-parse --short HEAD)
  - docker build --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=$BUILD_DATE --build-arg PGADMIN_VERSION=$PGADMIN_VERSION -t $IMAGE_NAME:build .

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Building master branch. Let's push the new build on dockerhub"
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag $IMAGE_NAME:build $IMAGE_NAME:latest
      docker tag $IMAGE_NAME:build $IMAGE_NAME:$PGADMIN_VERSION
      docker push $IMAGE_NAME:latest
    fi  
