sudo: required

services:
  - docker

# From https://docs.travis-ci.com/user/customizing-the-build/
# install: true

# 'bash' is not a travis language. See https://docs.travis-ci.com/user/languages/
language: generic

# env:
#   global:
#     - IMAGE_NAME=biarms/pgadmin4
#     - VERSION=3.4

matrix:
    include:
        - os: linux
          env:
           - BUILD_ARCH=arm32v6
           - QEMU_ARCH=arm
        - os: linux
          env:
           - BUILD_ARCH=arm32v7
           - QEMU_ARCH=arm
        - os: linux
          env:
           - BUILD_ARCH=arm64v8
           - QEMU_ARCH=aarch64

before_install:
  - VERSION=$(grep "ENV VERSION" Dockerfile | sed 's/.*=//')
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      echo "We are building the master branch: version is official version."
      IMAGE_VERSION="${VERSION}"
      BETA_MODE="false"
    else
      echo "We are not building the master branch (or we are in a PR mode). Building a beta version then"
      IMAGE_VERSION="${VERSION}-beta-${TRAVIS_BUILD_NUMBER}"
      BETA_MODE="true"
    fi
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # When https://github.com/docker/cli/pull/138 merged branch will be part of an official release:
  # docker manifest create biarms/mysql biarms/mysql-arm
  # docker manifest annotate biarms/mysql biarms/mysql-arm --os linux --arch arm
  # docker manifest push new-list-ref-name
  #
  # In the mean time, we use: https://github.com/estesp/manifest-tool
  # https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-arm64 &&
  - curl -L -o manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.8.0/manifest-tool-linux-386 &&
    chmod +x manifest-tool &&
    ls -l manifest-tool &&
    export PATH="$(pwd):$PATH" &&
    bash -c 'manifest-tool --version'

script:
  - export IMAGE_VERSION
  - echo "BUILD_ARCH=${BUILD_ARCH} - QEMU_ARCH=${QEMU_ARCH} - IMAGE_VERSION=${IMAGE_VERSION} - TRAVIS_BRANCH=${TRAVIS_BRANCH} - DOCKER_USERNAME=${DOCKER_USERNAME}"
  - make build test

after_success:
  - make tag push
  - >
    if [[ "${BETA_MODE}" == "false" ]]; then
      echo "Building master branch. Let's also push the 'latest' tag on docker hub"
      make push-latest
    fi
