os: linux
dist: bionic # On 20/05/2020, focal is still not listed on https://docs.travis-ci.com/user/reference/overview/, and Xenial 16.04 is always the default :(
language: shell

# https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
git:
  depth: false

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  # Skip every build (build will be done by CircleCI, because of TravisCI timeout)
  - echo "Travis build is disabled because of build timeout issue. The official build is therefore CircleCI for this project."
  - travis_terminate 0
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      echo "We are building the master branch: version is official version."
      BUILD_BETA_VERSION=""
    else
      echo "We are not building the master branch (or we are in a PR mode). Building a beta version then"
      BUILD_BETA_VERSION="-beta-travis" #${TRAVIS_BUILD_NUMBER}"
    fi
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH} - DOCKER_USERNAME=${DOCKER_USERNAME} - BUILD_BETA_VERSION=${BUILD_BETA_VERSION}"

jobs:
  include:
    - name: "arm32v6"
      env: MAKE_TARGET="test-arm32v6"
    - name: "arm32v7"
      env: MAKE_TARGET="test-arm32v7"
    - name: "arm64v8"
      env: MAKE_TARGET="test-arm64v8"
    - name: "amd64"
      env: MAKE_TARGET="test-amd64"
    - name: "buildx"
      env: MAKE_TARGET="buildx"

# before_script: travis_terminate 0

script:
  - BETA_VERSION=${BUILD_BETA_VERSION} make ${MAKE_TARGET}
